# fly.toml app configuration file generated for trench-bot-beta on 2025-08-14T03:02:07Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'trench-bot-beta'
primary_region = 'cdg'

[build]

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  cpu_kind = 'shared'
  cpus = 1
  memory_mb = 512
